void print_byte(char c);
int half_block_xor(unsigned char * result, const unsigned char * first, const unsigned char * second);
unsigned long remove_padding(unsigned char * result, unsigned long num_blocks, enum mode chosen, unsigned long total_file_size);
void split_byte(unsigned char * left_part, unsigned char * right_part, unsigned char whole);
void merge_byte(unsigned char * target, unsigned char left_part, unsigned char right_part);
void swap_bit(unsigned char * first, unsigned char * second, unsigned int pos_first, unsigned int pos_second);
void str_safe_copy(unsigned char * dest, unsigned char * src, unsigned long size);
void str_safe_print(unsigned char * to_print, unsigned long size);
int check_end_file(FILE *stream);
int check_last_block(FILE *stream);
void show_progress_data(struct timeval current_time);
void exit_message(int num_strings, ...);
double estimate_speed (struct timeval current_time);
void block_logging(block b, const char* message, unsigned long bcount);
double timeval_diff_seconds(struct timeval start, struct timeval end);
void block_xor(block *result, const block *first, const block *second);
long unsigned create_nonce(unsigned char nonce[BLOCKSIZE]);
void block_from_byte_array(block * b, unsigned char data[BLOCKSIZE]);
long unsigned derive_number_from_block(block * b);
void derive_block_from_number(long unsigned num, block *b);